const express = require('express');
const { body, param, query } = require('express-validator');
const authenticate = require('../middleware/authenticate'); const authorize = require('../middleware/authorize'); const validate = require('../middleware/validate');
const ctrl = require('../controllers/admin.controller');
const router = express.Router();
const pagination = [query('page').optional().isInt({ min: 1 }).toInt(), query('limit').optional().isInt({ min: 1, max: 100 }).toInt(), query('search').optional().isString().trim().isLength({ max: 100 })];
const id = param('id').isMongoId(); const slotFields = [body('instructorId').optional().isMongoId(), body('date').optional().isISO8601(), body('startTime').optional().matches(/^([01]\d|2[0-3]):[0-5]\d$/), body('endTime').optional().matches(/^([01]\d|2[0-3]):[0-5]\d$/), body('vehicleId').optional({ nullable: true }).isMongoId(), body('status').optional().isIn(['available', 'booked', 'cancelled'])];
router.use(authenticate, authorize('admin'));
router.get('/dashboard', ctrl.dashboard);
router.get('/users', [...pagination, query('role').optional().isIn(['student', 'instructor', 'admin']), query('isActive').optional().isBoolean()], validate, ctrl.listUsers);
router.get('/students', pagination, validate, ctrl.listStudents); router.get('/instructors', pagination, validate, ctrl.listInstructors);
router.patch('/users/:id', id, body('name').optional().isString().trim().isLength({ min: 2, max: 100 }), body('role').optional().isIn(['student', 'instructor', 'admin']), body('isActive').optional().isBoolean(), validate, ctrl.updateUser);
router.get('/courses', [...pagination, query('status').optional().isIn(['draft', 'published'])], validate, ctrl.listCourses);
router.get('/lessons', [...pagination, query('courseId').optional().isMongoId()], validate, ctrl.listLessons);
router.get('/bookings', [...pagination, query('status').optional().isIn(['pending', 'confirmed', 'rejected', 'cancelled']), query('studentId').optional().isMongoId(), query('instructorId').optional().isMongoId()], validate, ctrl.listBookings);
router.patch('/bookings/:id/cancel', id, body('reason').optional().isString().trim().isLength({ max: 500 }), validate, ctrl.cancelBooking);
router.get('/slots', [...pagination, query('status').optional().isIn(['available', 'booked', 'cancelled']), query('instructorId').optional().isMongoId(), query('date').optional().isISO8601()], validate, ctrl.listSlots);
router.post('/slots', body('instructorId').isMongoId(), body('date').isISO8601(), body('startTime').matches(/^([01]\d|2[0-3]):[0-5]\d$/), body('endTime').matches(/^([01]\d|2[0-3]):[0-5]\d$/), body('vehicleId').optional({ nullable: true }).isMongoId(), body('status').optional().isIn(['available', 'cancelled']), validate, ctrl.createSlot);
router.patch('/slots/:id', id, slotFields, validate, ctrl.updateSlot); router.delete('/slots/:id', id, validate, ctrl.deleteSlot);
router.get('/payments', [...pagination, query('status').optional().isIn(['created', 'paid', 'failed'])], validate, ctrl.listPayments);
module.exports = router;
