import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { getStudentDashboard } from '../../api/studentApi';
import { LoadingState, ErrorState, EmptyState } from '../../components/public/PublicPageState';

const StudentDashboard = () => {
  const [dashboard, setDashboard] = useState(null); const [error, setError] = useState('');
  useEffect(() => { getStudentDashboard().then(({ data }) => setDashboard(data.data)).catch((err) => setError(err.response?.data?.message || 'We could not load your dashboard.')); }, []);
  if (error) return <ErrorState message={error} />; if (!dashboard) return <LoadingState />;
  const { user, profile, enrollment, lessonProgress, upcomingBooking, recentNotifications } = dashboard;
  return <section className="space-y-5"><div><p className="text-sm text-primary-700">Student dashboard</p><h1 className="mt-1 text-2xl font-bold text-gray-900">Welcome, {user.name}</h1></div><div className="grid gap-5 lg:grid-cols-2"><article className="card"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-gray-900">Your details</h2><Link to="/student/profile" className="text-sm font-semibold text-primary-600">Edit</Link></div><p className="mt-3 text-sm text-gray-700">{user.email}</p><p className="mt-1 text-sm text-gray-600">{user.phone || 'Phone not added'}{profile?.drivingExperience ? ` · ${profile.drivingExperience}` : ''}</p></article><article className="card"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-gray-900">Current learning</h2><Link to="/student/courses" className="text-sm font-semibold text-primary-600">Courses</Link></div>{enrollment && lessonProgress ? <><p className="mt-3 text-sm font-medium text-gray-800">{enrollment.course?.title}</p><p className="mt-1 text-sm text-gray-600">{lessonProgress.completedLessons} / {lessonProgress.totalLessons} lessons completed · {lessonProgress.completionPercentage}%</p></> : <p className="mt-3 text-sm text-gray-600">Choose a course to start learning.</p>}</article></div><div className="grid gap-5 lg:grid-cols-2"><article className="card"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-gray-900">Book Slot</h2><Link to="/student/slots" className="btn-primary">Book Slot</Link></div>{upcomingBooking ? <p className="mt-3 text-sm text-gray-700">{upcomingBooking.instructorId?.name || 'Instructor'} · {upcomingBooking.slotId ? `${new Date(upcomingBooking.slotId.date).toLocaleDateString()} · ${upcomingBooking.slotId.startTime}–${upcomingBooking.slotId.endTime}` : 'Slot pending'} · <span className="capitalize">{upcomingBooking.status}</span></p> : <p className="mt-3 text-sm text-gray-600">No upcoming booking.</p>}</article><article className="card"><h2 className="font-semibold text-gray-900">Recent notifications</h2>{recentNotifications?.length ? <ul className="mt-3 space-y-2">{recentNotifications.map((notification) => <li key={notification._id} className="text-sm text-gray-700"><span className="font-medium">{notification.title}</span><span className="text-gray-500"> — {notification.message}</span></li>)}</ul> : <div className="mt-3"><EmptyState title="No notifications yet" message="Booking and purchase updates will appear here." /></div>}</article></div></section>;
};
export default StudentDashboard;
